"""Add table `users`

Revision ID: 20c43d4f40fa
Revises: 
Create Date: 2023-11-15 22:35:50.462473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c43d4f40fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), index=True),
        sa.Column('first_name', sa.String(150)),
        sa.Column('last_name', sa.String(150)),
        sa.Column('email', sa.String(150), unique=True, index=True),
        sa.Column('password', sa.String(128)),

        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(
        'users'
    )
    # ### end Alembic commands ###
