"""Add tables queues and queues_lifetime

Revision ID: 4654b3acb11c
Revises: c1ceae888882
Create Date: 2023-11-25 17:49:38.673505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4654b3acb11c'
down_revision: Union[str, None] = 'c1ceae888882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'queue_lifetime',
        sa.Column('id', sa.Integer(), index=True),
        sa.Column('lifetime', sa.Interval()),

        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'queues',
        sa.Column('id', sa.Integer(), index=True),
        sa.Column('key', sa.String(64), unique=True, index=True),

        sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id'), unique=True),
        sa.Column('queue_lifetime_id', sa.Integer, sa.ForeignKey('queue_lifetime.id'), unique=True),

        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue_lifetime')
    op.drop_table('queues')
    # ### end Alembic commands ###
