"""Alter table `user` add columns (`is_active`, `is_superuser`)

Revision ID: c1ceae888882
Revises: cc0df3de7ba8
Create Date: 2023-11-17 16:45:18.230304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c1ceae888882'
down_revision: Union[str, None] = 'cc0df3de7ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean, default=True))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###
