"""Add `tokens` table and make relationship `One to One` (`usres` and `tokens`)

Revision ID: cc0df3de7ba8
Revises: 20c43d4f40fa
Create Date: 2023-11-16 18:37:51.380782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0df3de7ba8'
down_revision: Union[str, None] = '20c43d4f40fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tokens',
        sa.Column('id', sa.Integer, index=True),
        sa.Column('key', sa.String(64), unique=True, index=True),
        sa.Column('date', sa.DateTime, server_default=sa.sql.func.now(), onupdate=sa.sql.func.now()),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id'), unique=True),

        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###
